# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GSAW.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 978)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1231, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.preprocess = QtWidgets.QWidget()
        self.preprocess.setObjectName("preprocess")
        self.label_105 = QtWidgets.QLabel(self.preprocess)
        self.label_105.setGeometry(QtCore.QRect(10, 0, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.frame_15 = QtWidgets.QFrame(self.preprocess)
        self.frame_15.setGeometry(QtCore.QRect(10, 50, 1191, 111))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.checkConversion = QtWidgets.QCheckBox(self.frame_15)
        self.checkConversion.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.checkConversion.setObjectName("checkConversion")
        self.checkWeight = QtWidgets.QCheckBox(self.frame_15)
        self.checkWeight.setGeometry(QtCore.QRect(330, 10, 231, 21))
        self.checkWeight.setObjectName("checkWeight")
        self.layoutWidget = QtWidgets.QWidget(self.frame_15)
        self.layoutWidget.setGeometry(QtCore.QRect(900, 30, 241, 78))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.radioMerge = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioMerge.setObjectName("radioMerge")
        self.verticalLayout_44.addWidget(self.radioMerge)
        self.radioConcat = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioConcat.setObjectName("radioConcat")
        self.verticalLayout_44.addWidget(self.radioConcat)
        self.checkJoin = QtWidgets.QCheckBox(self.frame_15)
        self.checkJoin.setGeometry(QtCore.QRect(870, 10, 191, 21))
        self.checkJoin.setObjectName("checkJoin")
        self.checkIndex = QtWidgets.QCheckBox(self.frame_15)
        self.checkIndex.setGeometry(QtCore.QRect(640, 10, 141, 21))
        self.checkIndex.setObjectName("checkIndex")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_15)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 30, 246, 79))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.radioFa2tFa = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioFa2tFa.setObjectName("radioFa2tFa")
        self.verticalLayout_43.addWidget(self.radioFa2tFa)
        self.radioFa2ms = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioFa2ms.setObjectName("radioFa2ms")
        self.verticalLayout_43.addWidget(self.radioFa2ms)
        self.radioFa2Fa = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioFa2Fa.setObjectName("radioFa2Fa")
        self.verticalLayout_43.addWidget(self.radioFa2Fa)
        self.horizontalLayout_14.addLayout(self.verticalLayout_43)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radiotFa2Fa = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radiotFa2Fa.setObjectName("radiotFa2Fa")
        self.verticalLayout_4.addWidget(self.radiotFa2Fa)
        self.radiotFa2ms = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radiotFa2ms.setObjectName("radiotFa2ms")
        self.verticalLayout_4.addWidget(self.radiotFa2ms)
        self.radioVCF2tFa = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioVCF2tFa.setObjectName("radioVCF2tFa")
        self.verticalLayout_4.addWidget(self.radioVCF2tFa)
        self.horizontalLayout_14.addLayout(self.verticalLayout_4)
        self.frameConversion = QtWidgets.QFrame(self.preprocess)
        self.frameConversion.setGeometry(QtCore.QRect(10, 170, 451, 651))
        self.frameConversion.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameConversion.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameConversion.setObjectName("frameConversion")
        self.layoutWidget_122 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_122.setGeometry(QtCore.QRect(10, 70, 431, 25))
        self.layoutWidget_122.setObjectName("layoutWidget_122")
        self.horizontalLayout_135 = QtWidgets.QHBoxLayout(self.layoutWidget_122)
        self.horizontalLayout_135.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_135.setObjectName("horizontalLayout_135")
        self.labelOutputConv = QtWidgets.QLabel(self.layoutWidget_122)
        self.labelOutputConv.setObjectName("labelOutputConv")
        self.horizontalLayout_135.addWidget(self.labelOutputConv)
        self.lineOutputConv = QtWidgets.QLineEdit(self.layoutWidget_122)
        self.lineOutputConv.setObjectName("lineOutputConv")
        self.horizontalLayout_135.addWidget(self.lineOutputConv)
        self.layoutWidget_123 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_123.setGeometry(QtCore.QRect(10, 100, 431, 31))
        self.layoutWidget_123.setObjectName("layoutWidget_123")
        self.horizontalLayout_136 = QtWidgets.QHBoxLayout(self.layoutWidget_123)
        self.horizontalLayout_136.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_136.setObjectName("horizontalLayout_136")
        self.label_107 = QtWidgets.QLabel(self.layoutWidget_123)
        self.label_107.setObjectName("label_107")
        self.horizontalLayout_136.addWidget(self.label_107)
        self.lineScaffoldConv = QtWidgets.QLineEdit(self.layoutWidget_123)
        self.lineScaffoldConv.setObjectName("lineScaffoldConv")
        self.horizontalLayout_136.addWidget(self.lineScaffoldConv)
        self.openScaffoldConv = QtWidgets.QPushButton(self.layoutWidget_123)
        self.openScaffoldConv.setObjectName("openScaffoldConv")
        self.horizontalLayout_136.addWidget(self.openScaffoldConv)
        self.layoutWidget_124 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_124.setGeometry(QtCore.QRect(10, 40, 431, 25))
        self.layoutWidget_124.setObjectName("layoutWidget_124")
        self.horizontalLayout_137 = QtWidgets.QHBoxLayout(self.layoutWidget_124)
        self.horizontalLayout_137.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_137.setObjectName("horizontalLayout_137")
        self.label_108 = QtWidgets.QLabel(self.layoutWidget_124)
        self.label_108.setObjectName("label_108")
        self.horizontalLayout_137.addWidget(self.label_108)
        self.lineInputConv = QtWidgets.QLineEdit(self.layoutWidget_124)
        self.lineInputConv.setObjectName("lineInputConv")
        self.horizontalLayout_137.addWidget(self.lineInputConv)
        self.openInputConv = QtWidgets.QPushButton(self.layoutWidget_124)
        self.openInputConv.setObjectName("openInputConv")
        self.horizontalLayout_137.addWidget(self.openInputConv)
        self.label_110 = QtWidgets.QLabel(self.frameConversion)
        self.label_110.setGeometry(QtCore.QRect(10, 10, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_110.setFont(font)
        self.label_110.setObjectName("label_110")
        self.layoutWidget_135 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_135.setGeometry(QtCore.QRect(10, 140, 431, 25))
        self.layoutWidget_135.setObjectName("layoutWidget_135")
        self.horizontalLayout_150 = QtWidgets.QHBoxLayout(self.layoutWidget_135)
        self.horizontalLayout_150.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_150.setObjectName("horizontalLayout_150")
        self.checkMaskConv = QtWidgets.QCheckBox(self.layoutWidget_135)
        self.checkMaskConv.setObjectName("checkMaskConv")
        self.horizontalLayout_150.addWidget(self.checkMaskConv)
        self.lineMaskConv = QtWidgets.QLineEdit(self.layoutWidget_135)
        self.lineMaskConv.setObjectName("lineMaskConv")
        self.horizontalLayout_150.addWidget(self.lineMaskConv)
        self.openMaskConv = QtWidgets.QPushButton(self.layoutWidget_135)
        self.openMaskConv.setObjectName("openMaskConv")
        self.horizontalLayout_150.addWidget(self.openMaskConv)
        self.label_42 = QtWidgets.QLabel(self.frameConversion)
        self.label_42.setGeometry(QtCore.QRect(10, 310, 191, 16))
        self.label_42.setObjectName("label_42")
        self.layoutWidget_48 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_48.setGeometry(QtCore.QRect(30, 330, 138, 50))
        self.layoutWidget_48.setObjectName("layoutWidget_48")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget_48)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.radioWindowLengthConv1 = QtWidgets.QRadioButton(self.layoutWidget_48)
        self.radioWindowLengthConv1.setObjectName("radioWindowLengthConv1")
        self.verticalLayout_22.addWidget(self.radioWindowLengthConv1)
        self.radioWindowLengthConv2 = QtWidgets.QRadioButton(self.layoutWidget_48)
        self.radioWindowLengthConv2.setObjectName("radioWindowLengthConv2")
        self.verticalLayout_22.addWidget(self.radioWindowLengthConv2)
        self.layoutWidget_49 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_49.setGeometry(QtCore.QRect(10, 420, 431, 25))
        self.layoutWidget_49.setObjectName("layoutWidget_49")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout(self.layoutWidget_49)
        self.horizontalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_49)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_60.addWidget(self.label_43)
        self.lineSamplesPopsConv = QtWidgets.QLineEdit(self.layoutWidget_49)
        self.lineSamplesPopsConv.setObjectName("lineSamplesPopsConv")
        self.horizontalLayout_60.addWidget(self.lineSamplesPopsConv)
        self.checkOrderSamplesConv = QtWidgets.QCheckBox(self.frameConversion)
        self.checkOrderSamplesConv.setGeometry(QtCore.QRect(10, 450, 181, 21))
        self.checkOrderSamplesConv.setObjectName("checkOrderSamplesConv")
        self.layoutWidget_50 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_50.setGeometry(QtCore.QRect(30, 470, 231, 25))
        self.layoutWidget_50.setObjectName("layoutWidget_50")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout(self.layoutWidget_50)
        self.horizontalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.labelOrderSamplesConv = QtWidgets.QLabel(self.layoutWidget_50)
        self.labelOrderSamplesConv.setObjectName("labelOrderSamplesConv")
        self.horizontalLayout_61.addWidget(self.labelOrderSamplesConv)
        self.lineOrderSamplesConv = QtWidgets.QLineEdit(self.layoutWidget_50)
        self.lineOrderSamplesConv.setObjectName("lineOrderSamplesConv")
        self.horizontalLayout_61.addWidget(self.lineOrderSamplesConv)
        self.layoutWidget_51 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_51.setGeometry(QtCore.QRect(10, 390, 241, 25))
        self.layoutWidget_51.setObjectName("layoutWidget_51")
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout(self.layoutWidget_51)
        self.horizontalLayout_62.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_51)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_62.addWidget(self.label_44)
        self.lineTotalPopsConv = QtWidgets.QLineEdit(self.layoutWidget_51)
        self.lineTotalPopsConv.setObjectName("lineTotalPopsConv")
        self.horizontalLayout_62.addWidget(self.lineTotalPopsConv)
        self.layoutWidget_58 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_58.setGeometry(QtCore.QRect(30, 500, 411, 25))
        self.layoutWidget_58.setObjectName("layoutWidget_58")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout(self.layoutWidget_58)
        self.horizontalLayout_63.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.labelOrderSamplesConv2 = QtWidgets.QLabel(self.layoutWidget_58)
        self.labelOrderSamplesConv2.setObjectName("labelOrderSamplesConv2")
        self.horizontalLayout_63.addWidget(self.labelOrderSamplesConv2)
        self.lineOrderSamplesConv2 = QtWidgets.QLineEdit(self.layoutWidget_58)
        self.lineOrderSamplesConv2.setObjectName("lineOrderSamplesConv2")
        self.horizontalLayout_63.addWidget(self.lineOrderSamplesConv2)
        self.checkOutgroupConv = QtWidgets.QCheckBox(self.frameConversion)
        self.checkOutgroupConv.setGeometry(QtCore.QRect(10, 280, 131, 21))
        self.checkOutgroupConv.setObjectName("checkOutgroupConv")
        self.checkUnknownPosConv = QtWidgets.QCheckBox(self.frameConversion)
        self.checkUnknownPosConv.setGeometry(QtCore.QRect(10, 250, 191, 21))
        self.checkUnknownPosConv.setObjectName("checkUnknownPosConv")
        self.layoutWidget_59 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_59.setGeometry(QtCore.QRect(10, 170, 431, 37))
        self.layoutWidget_59.setObjectName("layoutWidget_59")
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout(self.layoutWidget_59)
        self.horizontalLayout_70.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.checkCoordConv = QtWidgets.QCheckBox(self.layoutWidget_59)
        self.checkCoordConv.setObjectName("checkCoordConv")
        self.horizontalLayout_70.addWidget(self.checkCoordConv)
        self.lineCoordConv = QtWidgets.QLineEdit(self.layoutWidget_59)
        self.lineCoordConv.setObjectName("lineCoordConv")
        self.horizontalLayout_70.addWidget(self.lineCoordConv)
        self.openCoordConv = QtWidgets.QPushButton(self.layoutWidget_59)
        self.openCoordConv.setObjectName("openCoordConv")
        self.horizontalLayout_70.addWidget(self.openCoordConv)
        self.layoutWidget_60 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_60.setGeometry(QtCore.QRect(10, 560, 251, 25))
        self.layoutWidget_60.setObjectName("layoutWidget_60")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout(self.layoutWidget_60)
        self.horizontalLayout_71.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.checkSlideConv = QtWidgets.QCheckBox(self.layoutWidget_60)
        self.checkSlideConv.setObjectName("checkSlideConv")
        self.horizontalLayout_71.addWidget(self.checkSlideConv)
        self.lineSlideConv = QtWidgets.QLineEdit(self.layoutWidget_60)
        self.lineSlideConv.setObjectName("lineSlideConv")
        self.horizontalLayout_71.addWidget(self.lineSlideConv)
        self.layoutWidget_61 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_61.setGeometry(QtCore.QRect(10, 530, 251, 25))
        self.layoutWidget_61.setObjectName("layoutWidget_61")
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout(self.layoutWidget_61)
        self.horizontalLayout_72.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.checkWindowSizeConv = QtWidgets.QCheckBox(self.layoutWidget_61)
        self.checkWindowSizeConv.setObjectName("checkWindowSizeConv")
        self.horizontalLayout_72.addWidget(self.checkWindowSizeConv)
        self.lineWindowSizeConv = QtWidgets.QLineEdit(self.layoutWidget_61)
        self.lineWindowSizeConv.setObjectName("lineWindowSizeConv")
        self.horizontalLayout_72.addWidget(self.lineWindowSizeConv)
        self.checkIUPACConv = QtWidgets.QCheckBox(self.frameConversion)
        self.checkIUPACConv.setGeometry(QtCore.QRect(10, 590, 431, 21))
        self.checkIUPACConv.setObjectName("checkIUPACConv")
        self.updateConv = QtWidgets.QPushButton(self.frameConversion)
        self.updateConv.setGeometry(QtCore.QRect(160, 620, 131, 23))
        self.updateConv.setObjectName("updateConv")
        self.layoutWidget_63 = QtWidgets.QWidget(self.frameConversion)
        self.layoutWidget_63.setGeometry(QtCore.QRect(10, 210, 431, 37))
        self.layoutWidget_63.setObjectName("layoutWidget_63")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout(self.layoutWidget_63)
        self.horizontalLayout_75.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.checkWeightConv = QtWidgets.QCheckBox(self.layoutWidget_63)
        self.checkWeightConv.setObjectName("checkWeightConv")
        self.horizontalLayout_75.addWidget(self.checkWeightConv)
        self.lineWeightConv = QtWidgets.QLineEdit(self.layoutWidget_63)
        self.lineWeightConv.setObjectName("lineWeightConv")
        self.horizontalLayout_75.addWidget(self.lineWeightConv)
        self.openWeightConv = QtWidgets.QPushButton(self.layoutWidget_63)
        self.openWeightConv.setObjectName("openWeightConv")
        self.horizontalLayout_75.addWidget(self.openWeightConv)
        self.frameWeight = QtWidgets.QFrame(self.preprocess)
        self.frameWeight.setGeometry(QtCore.QRect(470, 420, 731, 401))
        self.frameWeight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameWeight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameWeight.setObjectName("frameWeight")
        self.labelCodeWeight = QtWidgets.QLabel(self.frameWeight)
        self.labelCodeWeight.setGeometry(QtCore.QRect(39, 200, 491, 23))
        self.labelCodeWeight.setObjectName("labelCodeWeight")
        self.layoutWidget_127 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_127.setGeometry(QtCore.QRect(9, 140, 491, 25))
        self.layoutWidget_127.setObjectName("layoutWidget_127")
        self.horizontalLayout_141 = QtWidgets.QHBoxLayout(self.layoutWidget_127)
        self.horizontalLayout_141.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_141.setObjectName("horizontalLayout_141")
        self.checkGFFWeight = QtWidgets.QCheckBox(self.layoutWidget_127)
        self.checkGFFWeight.setObjectName("checkGFFWeight")
        self.horizontalLayout_141.addWidget(self.checkGFFWeight)
        self.lineGFFWeight = QtWidgets.QLineEdit(self.layoutWidget_127)
        self.lineGFFWeight.setObjectName("lineGFFWeight")
        self.horizontalLayout_141.addWidget(self.lineGFFWeight)
        self.openGFFWeight = QtWidgets.QPushButton(self.layoutWidget_127)
        self.openGFFWeight.setObjectName("openGFFWeight")
        self.horizontalLayout_141.addWidget(self.openGFFWeight)
        self.labelCriteriaWeight = QtWidgets.QLabel(self.frameWeight)
        self.labelCriteriaWeight.setGeometry(QtCore.QRect(39, 250, 291, 23))
        self.labelCriteriaWeight.setObjectName("labelCriteriaWeight")
        self.layoutWidget_128 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_128.setGeometry(QtCore.QRect(40, 170, 381, 25))
        self.layoutWidget_128.setObjectName("layoutWidget_128")
        self.horizontalLayout_142 = QtWidgets.QHBoxLayout(self.layoutWidget_128)
        self.horizontalLayout_142.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_142.setObjectName("horizontalLayout_142")
        self.labelTypeWeight = QtWidgets.QLabel(self.layoutWidget_128)
        self.labelTypeWeight.setObjectName("labelTypeWeight")
        self.horizontalLayout_142.addWidget(self.labelTypeWeight)
        self.lineTypeWeight = QtWidgets.QLineEdit(self.layoutWidget_128)
        self.lineTypeWeight.setObjectName("lineTypeWeight")
        self.horizontalLayout_142.addWidget(self.lineTypeWeight)
        self.label_109 = QtWidgets.QLabel(self.frameWeight)
        self.label_109.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")
        self.layoutWidget_129 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_129.setGeometry(QtCore.QRect(10, 40, 491, 25))
        self.layoutWidget_129.setObjectName("layoutWidget_129")
        self.horizontalLayout_143 = QtWidgets.QHBoxLayout(self.layoutWidget_129)
        self.horizontalLayout_143.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_143.setObjectName("horizontalLayout_143")
        self.labelInputWeight = QtWidgets.QLabel(self.layoutWidget_129)
        self.labelInputWeight.setObjectName("labelInputWeight")
        self.horizontalLayout_143.addWidget(self.labelInputWeight)
        self.lineInputWeight = QtWidgets.QLineEdit(self.layoutWidget_129)
        self.lineInputWeight.setObjectName("lineInputWeight")
        self.horizontalLayout_143.addWidget(self.lineInputWeight)
        self.openInputWeight = QtWidgets.QPushButton(self.layoutWidget_129)
        self.openInputWeight.setObjectName("openInputWeight")
        self.horizontalLayout_143.addWidget(self.openInputWeight)
        self.layoutWidget_130 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_130.setGeometry(QtCore.QRect(10, 70, 491, 25))
        self.layoutWidget_130.setObjectName("layoutWidget_130")
        self.horizontalLayout_144 = QtWidgets.QHBoxLayout(self.layoutWidget_130)
        self.horizontalLayout_144.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_144.setObjectName("horizontalLayout_144")
        self.labelOutputWeight = QtWidgets.QLabel(self.layoutWidget_130)
        self.labelOutputWeight.setObjectName("labelOutputWeight")
        self.horizontalLayout_144.addWidget(self.labelOutputWeight)
        self.lineOutputWeight = QtWidgets.QLineEdit(self.layoutWidget_130)
        self.lineOutputWeight.setObjectName("lineOutputWeight")
        self.horizontalLayout_144.addWidget(self.lineOutputWeight)
        self.layoutWidget_133 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_133.setGeometry(QtCore.QRect(10, 340, 481, 25))
        self.layoutWidget_133.setObjectName("layoutWidget_133")
        self.horizontalLayout_148 = QtWidgets.QHBoxLayout(self.layoutWidget_133)
        self.horizontalLayout_148.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_148.setObjectName("horizontalLayout_148")
        self.checkMaskWeight = QtWidgets.QCheckBox(self.layoutWidget_133)
        self.checkMaskWeight.setObjectName("checkMaskWeight")
        self.horizontalLayout_148.addWidget(self.checkMaskWeight)
        self.lineMaskWeight = QtWidgets.QLineEdit(self.layoutWidget_133)
        self.lineMaskWeight.setObjectName("lineMaskWeight")
        self.horizontalLayout_148.addWidget(self.lineMaskWeight)
        self.openMaskWeight = QtWidgets.QPushButton(self.layoutWidget_133)
        self.openMaskWeight.setObjectName("openMaskWeight")
        self.horizontalLayout_148.addWidget(self.openMaskWeight)
        self.layoutWidget_134 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_134.setGeometry(QtCore.QRect(10, 370, 481, 25))
        self.layoutWidget_134.setObjectName("layoutWidget_134")
        self.horizontalLayout_149 = QtWidgets.QHBoxLayout(self.layoutWidget_134)
        self.horizontalLayout_149.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_149.setObjectName("horizontalLayout_149")
        self.checkRegionsWeight = QtWidgets.QCheckBox(self.layoutWidget_134)
        self.checkRegionsWeight.setObjectName("checkRegionsWeight")
        self.horizontalLayout_149.addWidget(self.checkRegionsWeight)
        self.lineRegionsWeight = QtWidgets.QLineEdit(self.layoutWidget_134)
        self.lineRegionsWeight.setObjectName("lineRegionsWeight")
        self.horizontalLayout_149.addWidget(self.lineRegionsWeight)
        self.openRegionsWeight = QtWidgets.QPushButton(self.layoutWidget_134)
        self.openRegionsWeight.setObjectName("openRegionsWeight")
        self.horizontalLayout_149.addWidget(self.openRegionsWeight)
        self.updateWeight = QtWidgets.QPushButton(self.frameWeight)
        self.updateWeight.setGeometry(QtCore.QRect(570, 370, 131, 23))
        self.updateWeight.setObjectName("updateWeight")
        self.layoutWidget_143 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget_143.setGeometry(QtCore.QRect(10, 100, 491, 31))
        self.layoutWidget_143.setObjectName("layoutWidget_143")
        self.horizontalLayout_158 = QtWidgets.QHBoxLayout(self.layoutWidget_143)
        self.horizontalLayout_158.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_158.setObjectName("horizontalLayout_158")
        self.labelScaffoldWeight = QtWidgets.QLabel(self.layoutWidget_143)
        self.labelScaffoldWeight.setObjectName("labelScaffoldWeight")
        self.horizontalLayout_158.addWidget(self.labelScaffoldWeight)
        self.lineScaffoldWeight = QtWidgets.QLineEdit(self.layoutWidget_143)
        self.lineScaffoldWeight.setObjectName("lineScaffoldWeight")
        self.horizontalLayout_158.addWidget(self.lineScaffoldWeight)
        self.openScaffoldWeight = QtWidgets.QPushButton(self.layoutWidget_143)
        self.openScaffoldWeight.setObjectName("openScaffoldWeight")
        self.horizontalLayout_158.addWidget(self.openScaffoldWeight)
        self.layoutWidget2 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget2.setGeometry(QtCore.QRect(60, 220, 661, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_73.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.radioCode1Weight = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioCode1Weight.setObjectName("radioCode1Weight")
        self.horizontalLayout_73.addWidget(self.radioCode1Weight)
        self.radioCode3Weight = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioCode3Weight.setObjectName("radioCode3Weight")
        self.horizontalLayout_73.addWidget(self.radioCode3Weight)
        self.radioCode2Weight = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioCode2Weight.setObjectName("radioCode2Weight")
        self.horizontalLayout_73.addWidget(self.radioCode2Weight)
        self.horizontalLayout_157 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_157.setObjectName("horizontalLayout_157")
        self.radioCode4Weight = QtWidgets.QRadioButton(self.layoutWidget2)
        self.radioCode4Weight.setObjectName("radioCode4Weight")
        self.horizontalLayout_157.addWidget(self.radioCode4Weight)
        self.lineCode4Weight = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineCode4Weight.setObjectName("lineCode4Weight")
        self.horizontalLayout_157.addWidget(self.lineCode4Weight)
        self.horizontalLayout_73.addLayout(self.horizontalLayout_157)
        self.layoutWidget3 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget3.setGeometry(QtCore.QRect(60, 270, 575, 37))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_74.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.radioMaxWeight = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioMaxWeight.setObjectName("radioMaxWeight")
        self.horizontalLayout_74.addWidget(self.radioMaxWeight)
        self.radioFirstWeight = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioFirstWeight.setObjectName("radioFirstWeight")
        self.horizontalLayout_74.addWidget(self.radioFirstWeight)
        self.radioLongWeight = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioLongWeight.setObjectName("radioLongWeight")
        self.horizontalLayout_74.addWidget(self.radioLongWeight)
        self.radioMinWeight = QtWidgets.QRadioButton(self.layoutWidget3)
        self.radioMinWeight.setObjectName("radioMinWeight")
        self.horizontalLayout_74.addWidget(self.radioMinWeight)
        self.layoutWidget4 = QtWidgets.QWidget(self.frameWeight)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 310, 483, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkOutgroupWeight = QtWidgets.QCheckBox(self.layoutWidget4)
        self.checkOutgroupWeight.setObjectName("checkOutgroupWeight")
        self.horizontalLayout_15.addWidget(self.checkOutgroupWeight)
        self.horizontalLayout_147 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_147.setObjectName("horizontalLayout_147")
        self.labelOutgroupWeight = QtWidgets.QLabel(self.layoutWidget4)
        self.labelOutgroupWeight.setObjectName("labelOutgroupWeight")
        self.horizontalLayout_147.addWidget(self.labelOutgroupWeight)
        self.lineOutgroupWeight = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineOutgroupWeight.setObjectName("lineOutgroupWeight")
        self.horizontalLayout_147.addWidget(self.lineOutgroupWeight)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_147)
        self.frameJoin = QtWidgets.QFrame(self.preprocess)
        self.frameJoin.setGeometry(QtCore.QRect(910, 170, 291, 131))
        self.frameJoin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameJoin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameJoin.setObjectName("frameJoin")
        self.label_114 = QtWidgets.QLabel(self.frameJoin)
        self.label_114.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_114.setFont(font)
        self.label_114.setObjectName("label_114")
        self.layoutWidget_136 = QtWidgets.QWidget(self.frameJoin)
        self.layoutWidget_136.setGeometry(QtCore.QRect(10, 40, 271, 25))
        self.layoutWidget_136.setObjectName("layoutWidget_136")
        self.horizontalLayout_146 = QtWidgets.QHBoxLayout(self.layoutWidget_136)
        self.horizontalLayout_146.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_146.setObjectName("horizontalLayout_146")
        self.labelInputJoin = QtWidgets.QLabel(self.layoutWidget_136)
        self.labelInputJoin.setObjectName("labelInputJoin")
        self.horizontalLayout_146.addWidget(self.labelInputJoin)
        self.lineInputJoin = QtWidgets.QLineEdit(self.layoutWidget_136)
        self.lineInputJoin.setObjectName("lineInputJoin")
        self.horizontalLayout_146.addWidget(self.lineInputJoin)
        self.openInputJoin = QtWidgets.QPushButton(self.layoutWidget_136)
        self.openInputJoin.setObjectName("openInputJoin")
        self.horizontalLayout_146.addWidget(self.openInputJoin)
        self.layoutWidget_137 = QtWidgets.QWidget(self.frameJoin)
        self.layoutWidget_137.setGeometry(QtCore.QRect(10, 70, 271, 25))
        self.layoutWidget_137.setObjectName("layoutWidget_137")
        self.horizontalLayout_151 = QtWidgets.QHBoxLayout(self.layoutWidget_137)
        self.horizontalLayout_151.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_151.setObjectName("horizontalLayout_151")
        self.label_117 = QtWidgets.QLabel(self.layoutWidget_137)
        self.label_117.setObjectName("label_117")
        self.horizontalLayout_151.addWidget(self.label_117)
        self.lineOutputJoin = QtWidgets.QLineEdit(self.layoutWidget_137)
        self.lineOutputJoin.setObjectName("lineOutputJoin")
        self.horizontalLayout_151.addWidget(self.lineOutputJoin)
        self.updateJoin = QtWidgets.QPushButton(self.frameJoin)
        self.updateJoin.setGeometry(QtCore.QRect(90, 100, 131, 23))
        self.updateJoin.setObjectName("updateJoin")
        self.frameIndex = QtWidgets.QFrame(self.preprocess)
        self.frameIndex.setGeometry(QtCore.QRect(910, 310, 291, 101))
        self.frameIndex.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIndex.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIndex.setObjectName("frameIndex")
        self.label_118 = QtWidgets.QLabel(self.frameIndex)
        self.label_118.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_118.setFont(font)
        self.label_118.setObjectName("label_118")
        self.layoutWidget_138 = QtWidgets.QWidget(self.frameIndex)
        self.layoutWidget_138.setGeometry(QtCore.QRect(10, 40, 271, 25))
        self.layoutWidget_138.setObjectName("layoutWidget_138")
        self.horizontalLayout_152 = QtWidgets.QHBoxLayout(self.layoutWidget_138)
        self.horizontalLayout_152.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_152.setObjectName("horizontalLayout_152")
        self.labelInputIndex = QtWidgets.QLabel(self.layoutWidget_138)
        self.labelInputIndex.setObjectName("labelInputIndex")
        self.horizontalLayout_152.addWidget(self.labelInputIndex)
        self.lineInputIndex = QtWidgets.QLineEdit(self.layoutWidget_138)
        self.lineInputIndex.setObjectName("lineInputIndex")
        self.horizontalLayout_152.addWidget(self.lineInputIndex)
        self.openInputIndex = QtWidgets.QPushButton(self.layoutWidget_138)
        self.openInputIndex.setObjectName("openInputIndex")
        self.horizontalLayout_152.addWidget(self.openInputIndex)
        self.updateIndex = QtWidgets.QPushButton(self.frameIndex)
        self.updateIndex.setGeometry(QtCore.QRect(90, 70, 131, 23))
        self.updateIndex.setObjectName("updateIndex")
        self.frameVCF = QtWidgets.QFrame(self.preprocess)
        self.frameVCF.setGeometry(QtCore.QRect(470, 170, 431, 241))
        self.frameVCF.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameVCF.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameVCF.setObjectName("frameVCF")
        self.label_120 = QtWidgets.QLabel(self.frameVCF)
        self.label_120.setGeometry(QtCore.QRect(10, 10, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_120.setFont(font)
        self.label_120.setObjectName("label_120")
        self.layoutWidget_139 = QtWidgets.QWidget(self.frameVCF)
        self.layoutWidget_139.setGeometry(QtCore.QRect(10, 40, 411, 25))
        self.layoutWidget_139.setObjectName("layoutWidget_139")
        self.horizontalLayout_153 = QtWidgets.QHBoxLayout(self.layoutWidget_139)
        self.horizontalLayout_153.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_153.setObjectName("horizontalLayout_153")
        self.label_121 = QtWidgets.QLabel(self.layoutWidget_139)
        self.label_121.setObjectName("label_121")
        self.horizontalLayout_153.addWidget(self.label_121)
        self.lineInputVCF = QtWidgets.QLineEdit(self.layoutWidget_139)
        self.lineInputVCF.setObjectName("lineInputVCF")
        self.horizontalLayout_153.addWidget(self.lineInputVCF)
        self.openInputVCF = QtWidgets.QPushButton(self.layoutWidget_139)
        self.openInputVCF.setObjectName("openInputVCF")
        self.horizontalLayout_153.addWidget(self.openInputVCF)
        self.layoutWidget_140 = QtWidgets.QWidget(self.frameVCF)
        self.layoutWidget_140.setGeometry(QtCore.QRect(10, 120, 411, 31))
        self.layoutWidget_140.setObjectName("layoutWidget_140")
        self.horizontalLayout_154 = QtWidgets.QHBoxLayout(self.layoutWidget_140)
        self.horizontalLayout_154.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_154.setObjectName("horizontalLayout_154")
        self.labelOutputVCF = QtWidgets.QLabel(self.layoutWidget_140)
        self.labelOutputVCF.setObjectName("labelOutputVCF")
        self.horizontalLayout_154.addWidget(self.labelOutputVCF)
        self.lineOutputVCF = QtWidgets.QLineEdit(self.layoutWidget_140)
        self.lineOutputVCF.setObjectName("lineOutputVCF")
        self.horizontalLayout_154.addWidget(self.lineOutputVCF)
        self.layoutWidget_141 = QtWidgets.QWidget(self.frameVCF)
        self.layoutWidget_141.setGeometry(QtCore.QRect(10, 80, 411, 25))
        self.layoutWidget_141.setObjectName("layoutWidget_141")
        self.horizontalLayout_155 = QtWidgets.QHBoxLayout(self.layoutWidget_141)
        self.horizontalLayout_155.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_155.setObjectName("horizontalLayout_155")
        self.label_123 = QtWidgets.QLabel(self.layoutWidget_141)
        self.label_123.setObjectName("label_123")
        self.horizontalLayout_155.addWidget(self.label_123)
        self.lineInputRefFasta = QtWidgets.QLineEdit(self.layoutWidget_141)
        self.lineInputRefFasta.setObjectName("lineInputRefFasta")
        self.horizontalLayout_155.addWidget(self.lineInputRefFasta)
        self.openInputRefFasta = QtWidgets.QPushButton(self.layoutWidget_141)
        self.openInputRefFasta.setObjectName("openInputRefFasta")
        self.horizontalLayout_155.addWidget(self.openInputRefFasta)
        self.layoutWidget_142 = QtWidgets.QWidget(self.frameVCF)
        self.layoutWidget_142.setGeometry(QtCore.QRect(10, 160, 411, 31))
        self.layoutWidget_142.setObjectName("layoutWidget_142")
        self.horizontalLayout_156 = QtWidgets.QHBoxLayout(self.layoutWidget_142)
        self.horizontalLayout_156.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_156.setObjectName("horizontalLayout_156")
        self.label_124 = QtWidgets.QLabel(self.layoutWidget_142)
        self.label_124.setObjectName("label_124")
        self.horizontalLayout_156.addWidget(self.label_124)
        self.lineScaffoldVCF = QtWidgets.QLineEdit(self.layoutWidget_142)
        self.lineScaffoldVCF.setObjectName("lineScaffoldVCF")
        self.horizontalLayout_156.addWidget(self.lineScaffoldVCF)
        self.openScaffoldVCF = QtWidgets.QPushButton(self.layoutWidget_142)
        self.openScaffoldVCF.setObjectName("openScaffoldVCF")
        self.horizontalLayout_156.addWidget(self.openScaffoldVCF)
        self.updateVCF = QtWidgets.QPushButton(self.frameVCF)
        self.updateVCF.setGeometry(QtCore.QRect(150, 210, 131, 23))
        self.updateVCF.setObjectName("updateVCF")
        self.label_9 = QtWidgets.QLabel(self.preprocess)
        self.label_9.setGeometry(QtCore.QRect(1130, -10, 91, 81))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/GSAW_icon_small.png"))
        self.label_9.setObjectName("label_9")
        self.tabWidget.addTab(self.preprocess, "")
        self.mstatspop = QtWidgets.QWidget()
        self.mstatspop.setObjectName("mstatspop")
        self.frameOutput = QtWidgets.QFrame(self.mstatspop)
        self.frameOutput.setGeometry(QtCore.QRect(450, 50, 751, 171))
        self.frameOutput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOutput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOutput.setObjectName("frameOutput")
        self.label_7 = QtWidgets.QLabel(self.frameOutput)
        self.label_7.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frameOutput)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 59, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.layoutWidget5 = QtWidgets.QWidget(self.frameOutput)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 40, 401, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelOutput = QtWidgets.QLabel(self.layoutWidget5)
        self.labelOutput.setObjectName("labelOutput")
        self.horizontalLayout_2.addWidget(self.labelOutput)
        self.lineOutput = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineOutput.setObjectName("lineOutput")
        self.horizontalLayout_2.addWidget(self.lineOutput)
        self.updateOutput = QtWidgets.QPushButton(self.layoutWidget5)
        self.updateOutput.setObjectName("updateOutput")
        self.horizontalLayout_2.addWidget(self.updateOutput)
        self.layoutWidget6 = QtWidgets.QWidget(self.frameOutput)
        self.layoutWidget6.setGeometry(QtCore.QRect(30, 90, 721, 79))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioFormat0 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat0.setObjectName("radioFormat0")
        self.verticalLayout_2.addWidget(self.radioFormat0)
        self.radioFormat1 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat1.setObjectName("radioFormat1")
        self.verticalLayout_2.addWidget(self.radioFormat1)
        self.radioFormat2 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat2.setObjectName("radioFormat2")
        self.verticalLayout_2.addWidget(self.radioFormat2)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioFormat3 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat3.setObjectName("radioFormat3")
        self.verticalLayout_3.addWidget(self.radioFormat3)
        self.radioFormat4 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat4.setObjectName("radioFormat4")
        self.verticalLayout_3.addWidget(self.radioFormat4)
        self.radioFormat5 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat5.setObjectName("radioFormat5")
        self.verticalLayout_3.addWidget(self.radioFormat5)
        self.horizontalLayout_13.addLayout(self.verticalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.radioFormat6 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat6.setObjectName("radioFormat6")
        self.verticalLayout_9.addWidget(self.radioFormat6)
        self.radioFormat7 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat7.setObjectName("radioFormat7")
        self.verticalLayout_9.addWidget(self.radioFormat7)
        self.radioFormat10 = QtWidgets.QRadioButton(self.layoutWidget6)
        self.radioFormat10.setObjectName("radioFormat10")
        self.verticalLayout_9.addWidget(self.radioFormat10)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.frameMS = QtWidgets.QFrame(self.mstatspop)
        self.frameMS.setGeometry(QtCore.QRect(10, 470, 351, 351))
        self.frameMS.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMS.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMS.setObjectName("frameMS")
        self.label_12 = QtWidgets.QLabel(self.frameMS)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frameMS)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 40, 191, 25))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.lineMSlength = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineMSlength.setObjectName("lineMSlength")
        self.horizontalLayout_8.addWidget(self.lineMSlength)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frameMS)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 70, 251, 25))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkMSiter = QtWidgets.QCheckBox(self.layoutWidget_4)
        self.checkMSiter.setObjectName("checkMSiter")
        self.horizontalLayout_9.addWidget(self.checkMSiter)
        self.lineMSiter = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineMSiter.setObjectName("lineMSiter")
        self.horizontalLayout_9.addWidget(self.lineMSiter)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frameMS)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 100, 311, 25))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkMSratio = QtWidgets.QCheckBox(self.layoutWidget_5)
        self.checkMSratio.setObjectName("checkMSratio")
        self.horizontalLayout_11.addWidget(self.checkMSratio)
        self.lineMSratio = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineMSratio.setObjectName("lineMSratio")
        self.horizontalLayout_11.addWidget(self.lineMSratio)
        self.checkMSoutgroup = QtWidgets.QCheckBox(self.frameMS)
        self.checkMSoutgroup.setGeometry(QtCore.QRect(10, 160, 231, 21))
        self.checkMSoutgroup.setObjectName("checkMSoutgroup")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frameMS)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 190, 331, 25))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkMSRev = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.checkMSRev.setObjectName("checkMSRev")
        self.horizontalLayout_12.addWidget(self.checkMSRev)
        self.lineMSRev = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineMSRev.setObjectName("lineMSRev")
        self.horizontalLayout_12.addWidget(self.lineMSRev)
        self.updateMS = QtWidgets.QPushButton(self.frameMS)
        self.updateMS.setGeometry(QtCore.QRect(130, 320, 131, 23))
        self.updateMS.setObjectName("updateMS")
        self.layoutWidget7 = QtWidgets.QWidget(self.frameMS)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 130, 331, 25))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkMaskMS = QtWidgets.QCheckBox(self.layoutWidget7)
        self.checkMaskMS.setObjectName("checkMaskMS")
        self.horizontalLayout_10.addWidget(self.checkMaskMS)
        self.lineMaskMS = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineMaskMS.setObjectName("lineMaskMS")
        self.horizontalLayout_10.addWidget(self.lineMaskMS)
        self.openMaskMS = QtWidgets.QPushButton(self.layoutWidget7)
        self.openMaskMS.setObjectName("openMaskMS")
        self.horizontalLayout_10.addWidget(self.openMaskMS)
        self.frameFasta = QtWidgets.QFrame(self.mstatspop)
        self.frameFasta.setGeometry(QtCore.QRect(370, 470, 441, 351))
        self.frameFasta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFasta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameFasta.setObjectName("frameFasta")
        self.label_17 = QtWidgets.QLabel(self.frameFasta)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.layoutWidget_14 = QtWidgets.QWidget(self.frameFasta)
        self.layoutWidget_14.setGeometry(QtCore.QRect(10, 70, 341, 25))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.checkGFF = QtWidgets.QCheckBox(self.layoutWidget_14)
        self.checkGFF.setObjectName("checkGFF")
        self.horizontalLayout_20.addWidget(self.checkGFF)
        self.lineGFF = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.lineGFF.setObjectName("lineGFF")
        self.horizontalLayout_20.addWidget(self.lineGFF)
        self.openGFF = QtWidgets.QPushButton(self.layoutWidget_14)
        self.openGFF.setObjectName("openGFF")
        self.horizontalLayout_20.addWidget(self.openGFF)
        self.labelCode = QtWidgets.QLabel(self.frameFasta)
        self.labelCode.setGeometry(QtCore.QRect(40, 130, 391, 23))
        self.labelCode.setObjectName("labelCode")
        self.labelCriteria = QtWidgets.QLabel(self.frameFasta)
        self.labelCriteria.setGeometry(QtCore.QRect(40, 210, 291, 23))
        self.labelCriteria.setObjectName("labelCriteria")
        self.checkMaskFasta = QtWidgets.QCheckBox(self.frameFasta)
        self.checkMaskFasta.setGeometry(QtCore.QRect(10, 300, 271, 21))
        self.checkMaskFasta.setObjectName("checkMaskFasta")
        self.updateFasta = QtWidgets.QPushButton(self.frameFasta)
        self.updateFasta.setGeometry(QtCore.QRect(150, 320, 131, 23))
        self.updateFasta.setObjectName("updateFasta")
        self.checkIUPACFasta = QtWidgets.QCheckBox(self.frameFasta)
        self.checkIUPACFasta.setGeometry(QtCore.QRect(10, 40, 441, 21))
        self.checkIUPACFasta.setObjectName("checkIUPACFasta")
        self.layoutWidget8 = QtWidgets.QWidget(self.frameFasta)
        self.layoutWidget8.setGeometry(QtCore.QRect(41, 100, 311, 25))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.labelType = QtWidgets.QLabel(self.layoutWidget8)
        self.labelType.setObjectName("labelType")
        self.horizontalLayout_21.addWidget(self.labelType)
        self.lineType = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineType.setObjectName("lineType")
        self.horizontalLayout_21.addWidget(self.lineType)
        self.layoutWidget9 = QtWidgets.QWidget(self.frameFasta)
        self.layoutWidget9.setGeometry(QtCore.QRect(60, 150, 371, 56))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioCode1 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioCode1.setObjectName("radioCode1")
        self.verticalLayout_5.addWidget(self.radioCode1)
        self.radioCode3 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioCode3.setObjectName("radioCode3")
        self.verticalLayout_5.addWidget(self.radioCode3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioCode2 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioCode2.setObjectName("radioCode2")
        self.verticalLayout_11.addWidget(self.radioCode2)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioCode4 = QtWidgets.QRadioButton(self.layoutWidget9)
        self.radioCode4.setObjectName("radioCode4")
        self.horizontalLayout_22.addWidget(self.radioCode4)
        self.lineCode4 = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineCode4.setObjectName("lineCode4")
        self.horizontalLayout_22.addWidget(self.lineCode4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_18.addLayout(self.verticalLayout_11)
        self.layoutWidget10 = QtWidgets.QWidget(self.frameFasta)
        self.layoutWidget10.setGeometry(QtCore.QRect(60, 230, 341, 66))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioMax = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioMax.setObjectName("radioMax")
        self.verticalLayout_6.addWidget(self.radioMax)
        self.radioFirst = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioFirst.setObjectName("radioFirst")
        self.verticalLayout_6.addWidget(self.radioFirst)
        self.horizontalLayout_26.addLayout(self.verticalLayout_6)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioMin = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioMin.setObjectName("radioMin")
        self.verticalLayout_13.addWidget(self.radioMin)
        self.radioLong = QtWidgets.QRadioButton(self.layoutWidget10)
        self.radioLong.setObjectName("radioLong")
        self.verticalLayout_13.addWidget(self.radioLong)
        self.horizontalLayout_26.addLayout(self.verticalLayout_13)
        self.frameTFasta = QtWidgets.QFrame(self.mstatspop)
        self.frameTFasta.setGeometry(QtCore.QRect(820, 470, 381, 351))
        self.frameTFasta.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTFasta.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTFasta.setObjectName("frameTFasta")
        self.label_23 = QtWidgets.QLabel(self.frameTFasta)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.layoutWidget_12 = QtWidgets.QWidget(self.frameTFasta)
        self.layoutWidget_12.setGeometry(QtCore.QRect(10, 120, 361, 25))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkSlide = QtWidgets.QCheckBox(self.layoutWidget_12)
        self.checkSlide.setObjectName("checkSlide")
        self.horizontalLayout_4.addWidget(self.checkSlide)
        self.lineSlide = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineSlide.setObjectName("lineSlide")
        self.horizontalLayout_4.addWidget(self.lineSlide)
        self.label_24 = QtWidgets.QLabel(self.frameTFasta)
        self.label_24.setGeometry(QtCore.QRect(10, 180, 203, 23))
        self.label_24.setObjectName("label_24")
        self.layoutWidget_13 = QtWidgets.QWidget(self.frameTFasta)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 260, 361, 31))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_19.addWidget(self.label_26)
        self.lineWeights = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineWeights.setObjectName("lineWeights")
        self.horizontalLayout_19.addWidget(self.lineWeights)
        self.openWeights = QtWidgets.QPushButton(self.layoutWidget_13)
        self.openWeights.setObjectName("openWeights")
        self.horizontalLayout_19.addWidget(self.openWeights)
        self.updateTFasta = QtWidgets.QPushButton(self.frameTFasta)
        self.updateTFasta.setGeometry(QtCore.QRect(140, 320, 131, 23))
        self.updateTFasta.setObjectName("updateTFasta")
        self.layoutWidget11 = QtWidgets.QWidget(self.frameTFasta)
        self.layoutWidget11.setGeometry(QtCore.QRect(40, 200, 138, 50))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioWindowLengthTF1 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.radioWindowLengthTF1.setObjectName("radioWindowLengthTF1")
        self.verticalLayout_7.addWidget(self.radioWindowLengthTF1)
        self.radioWindowLengthTF2 = QtWidgets.QRadioButton(self.layoutWidget11)
        self.radioWindowLengthTF2.setObjectName("radioWindowLengthTF2")
        self.verticalLayout_7.addWidget(self.radioWindowLengthTF2)
        self.layoutWidget12 = QtWidgets.QWidget(self.frameTFasta)
        self.layoutWidget12.setGeometry(QtCore.QRect(10, 40, 361, 70))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.radioWindowSize = QtWidgets.QRadioButton(self.layoutWidget12)
        self.radioWindowSize.setObjectName("radioWindowSize")
        self.horizontalLayout_16.addWidget(self.radioWindowSize)
        self.lineWindowSize = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineWindowSize.setObjectName("lineWindowSize")
        self.horizontalLayout_16.addWidget(self.lineWindowSize)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.radioCoordTF = QtWidgets.QRadioButton(self.layoutWidget12)
        self.radioCoordTF.setObjectName("radioCoordTF")
        self.horizontalLayout_17.addWidget(self.radioCoordTF)
        self.lineCoordTF = QtWidgets.QLineEdit(self.layoutWidget12)
        self.lineCoordTF.setObjectName("lineCoordTF")
        self.horizontalLayout_17.addWidget(self.lineCoordTF)
        self.openCoordTF = QtWidgets.QPushButton(self.layoutWidget12)
        self.openCoordTF.setObjectName("openCoordTF")
        self.horizontalLayout_17.addWidget(self.openCoordTF)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.layoutWidget13 = QtWidgets.QWidget(self.frameTFasta)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 150, 361, 25))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget13)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.checkFirstWindowTF = QtWidgets.QCheckBox(self.layoutWidget13)
        self.checkFirstWindowTF.setObjectName("checkFirstWindowTF")
        self.horizontalLayout_25.addWidget(self.checkFirstWindowTF)
        self.lineFirstWindowTF = QtWidgets.QLineEdit(self.layoutWidget13)
        self.lineFirstWindowTF.setObjectName("lineFirstWindowTF")
        self.horizontalLayout_25.addWidget(self.lineFirstWindowTF)
        self.frameInput = QtWidgets.QFrame(self.mstatspop)
        self.frameInput.setGeometry(QtCore.QRect(10, 50, 431, 171))
        self.frameInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameInput.setObjectName("frameInput")
        self.label_4 = QtWidgets.QLabel(self.frameInput)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.frameInput)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 59, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget14 = QtWidgets.QWidget(self.frameInput)
        self.layoutWidget14.setGeometry(QtCore.QRect(30, 90, 316, 77))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioMS = QtWidgets.QRadioButton(self.layoutWidget14)
        self.radioMS.setObjectName("radioMS")
        self.verticalLayout.addWidget(self.radioMS)
        self.radioFasta = QtWidgets.QRadioButton(self.layoutWidget14)
        self.radioFasta.setObjectName("radioFasta")
        self.verticalLayout.addWidget(self.radioFasta)
        self.radioTFasta = QtWidgets.QRadioButton(self.layoutWidget14)
        self.radioTFasta.setObjectName("radioTFasta")
        self.verticalLayout.addWidget(self.radioTFasta)
        self.layoutWidget15 = QtWidgets.QWidget(self.frameInput)
        self.layoutWidget15.setGeometry(QtCore.QRect(10, 40, 391, 25))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget15)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget15)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineInput = QtWidgets.QLineEdit(self.layoutWidget15)
        self.lineInput.setObjectName("lineInput")
        self.horizontalLayout.addWidget(self.lineInput)
        self.openInput = QtWidgets.QPushButton(self.layoutWidget15)
        self.openInput.setObjectName("openInput")
        self.horizontalLayout.addWidget(self.openInput)
        self.frameParameters = QtWidgets.QFrame(self.mstatspop)
        self.frameParameters.setGeometry(QtCore.QRect(10, 230, 1191, 231))
        self.frameParameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParameters.setObjectName("frameParameters")
        self.checkOutgroup = QtWidgets.QCheckBox(self.frameParameters)
        self.checkOutgroup.setGeometry(QtCore.QRect(940, 70, 131, 21))
        self.checkOutgroup.setObjectName("checkOutgroup")
        self.checkUnknownPos = QtWidgets.QCheckBox(self.frameParameters)
        self.checkUnknownPos.setGeometry(QtCore.QRect(940, 40, 191, 21))
        self.checkUnknownPos.setObjectName("checkUnknownPos")
        self.label_10 = QtWidgets.QLabel(self.frameParameters)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 222, 23))
        self.label_10.setObjectName("label_10")
        self.label_8 = QtWidgets.QLabel(self.frameParameters)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.layoutWidget_15 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_15.setGeometry(QtCore.QRect(10, 40, 241, 25))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_23.addWidget(self.label_27)
        self.lineTotalSamples = QtWidgets.QLineEdit(self.layoutWidget_15)
        self.lineTotalSamples.setObjectName("lineTotalSamples")
        self.horizontalLayout_23.addWidget(self.lineTotalSamples)
        self.layoutWidget_16 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_16.setGeometry(QtCore.QRect(260, 40, 581, 25))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_24.addWidget(self.label_28)
        self.lineSamplesPops = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.lineSamplesPops.setObjectName("lineSamplesPops")
        self.horizontalLayout_24.addWidget(self.lineSamplesPops)
        self.layoutWidget_7 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_7.setGeometry(QtCore.QRect(40, 170, 231, 25))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_47.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.labelOrderSamples1 = QtWidgets.QLabel(self.layoutWidget_7)
        self.labelOrderSamples1.setObjectName("labelOrderSamples1")
        self.horizontalLayout_47.addWidget(self.labelOrderSamples1)
        self.lineOrderSamples1 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineOrderSamples1.setObjectName("lineOrderSamples1")
        self.horizontalLayout_47.addWidget(self.lineOrderSamples1)
        self.layoutWidget_17 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_17.setGeometry(QtCore.QRect(280, 170, 641, 25))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_48 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_48.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_48.setObjectName("horizontalLayout_48")
        self.labelOrderSamples2 = QtWidgets.QLabel(self.layoutWidget_17)
        self.labelOrderSamples2.setObjectName("labelOrderSamples2")
        self.horizontalLayout_48.addWidget(self.labelOrderSamples2)
        self.lineOrderSamples2 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.lineOrderSamples2.setObjectName("lineOrderSamples2")
        self.horizontalLayout_48.addWidget(self.lineOrderSamples2)
        self.checkOrderSamples = QtWidgets.QCheckBox(self.frameParameters)
        self.checkOrderSamples.setGeometry(QtCore.QRect(10, 150, 181, 21))
        self.checkOrderSamples.setObjectName("checkOrderSamples")
        self.layoutWidget_23 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_23.setGeometry(QtCore.QRect(560, 200, 151, 25))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.checkSeed = QtWidgets.QCheckBox(self.layoutWidget_23)
        self.checkSeed.setObjectName("checkSeed")
        self.horizontalLayout_44.addWidget(self.checkSeed)
        self.lineSeed = QtWidgets.QLineEdit(self.layoutWidget_23)
        self.lineSeed.setObjectName("lineSeed")
        self.horizontalLayout_44.addWidget(self.lineSeed)
        self.layoutWidget_22 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget_22.setGeometry(QtCore.QRect(10, 200, 291, 27))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self.horizontalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.checkPermWindows = QtWidgets.QCheckBox(self.layoutWidget_22)
        self.checkPermWindows.setObjectName("checkPermWindows")
        self.horizontalLayout_43.addWidget(self.checkPermWindows)
        self.linePermWindows = QtWidgets.QLineEdit(self.layoutWidget_22)
        self.linePermWindows.setObjectName("linePermWindows")
        self.horizontalLayout_43.addWidget(self.linePermWindows)
        self.updateGeneralParam = QtWidgets.QPushButton(self.frameParameters)
        self.updateGeneralParam.setGeometry(QtCore.QRect(1050, 200, 131, 23))
        self.updateGeneralParam.setObjectName("updateGeneralParam")
        self.layoutWidget16 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget16.setGeometry(QtCore.QRect(40, 120, 1031, 27))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget16)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkAltSpect = QtWidgets.QCheckBox(self.layoutWidget16)
        self.checkAltSpect.setObjectName("checkAltSpect")
        self.horizontalLayout_5.addWidget(self.checkAltSpect)
        self.lineAltSpect = QtWidgets.QLineEdit(self.layoutWidget16)
        self.lineAltSpect.setObjectName("lineAltSpect")
        self.horizontalLayout_5.addWidget(self.lineAltSpect)
        self.openAltSpect = QtWidgets.QPushButton(self.layoutWidget16)
        self.openAltSpect.setObjectName("openAltSpect")
        self.horizontalLayout_5.addWidget(self.openAltSpect)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkNullSpect = QtWidgets.QCheckBox(self.layoutWidget16)
        self.checkNullSpect.setObjectName("checkNullSpect")
        self.horizontalLayout_6.addWidget(self.checkNullSpect)
        self.lineNullSpect = QtWidgets.QLineEdit(self.layoutWidget16)
        self.lineNullSpect.setObjectName("lineNullSpect")
        self.horizontalLayout_6.addWidget(self.lineNullSpect)
        self.openNullSpect = QtWidgets.QPushButton(self.layoutWidget16)
        self.openNullSpect.setObjectName("openNullSpect")
        self.horizontalLayout_6.addWidget(self.openNullSpect)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.layoutWidget17 = QtWidgets.QWidget(self.frameParameters)
        self.layoutWidget17.setGeometry(QtCore.QRect(10, 70, 641, 25))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget17)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget17)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_3.addWidget(self.label_25)
        self.lineScaffold = QtWidgets.QLineEdit(self.layoutWidget17)
        self.lineScaffold.setObjectName("lineScaffold")
        self.horizontalLayout_3.addWidget(self.lineScaffold)
        self.openScaffold = QtWidgets.QPushButton(self.layoutWidget17)
        self.openScaffold.setObjectName("openScaffold")
        self.horizontalLayout_3.addWidget(self.openScaffold)
        self.label_2 = QtWidgets.QLabel(self.mstatspop)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.mstatspop, "")
        self.postprocess = QtWidgets.QWidget()
        self.postprocess.setObjectName("postprocess")
        self.label_111 = QtWidgets.QLabel(self.postprocess)
        self.label_111.setGeometry(QtCore.QRect(10, 0, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.tableWidget = QtWidgets.QTableWidget(self.postprocess)
        self.tableWidget.setGeometry(QtCore.QRect(10, 70, 1191, 751))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.label_14 = QtWidgets.QLabel(self.postprocess)
        self.label_14.setGeometry(QtCore.QRect(1130, -10, 91, 81))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/newPrefix/GSAW_icon_small.png"))
        self.label_14.setObjectName("label_14")
        self.tabWidget.addTab(self.postprocess, "")
        self.commandRun = QtWidgets.QTextBrowser(self.centralwidget)
        self.commandRun.setGeometry(QtCore.QRect(10, 870, 1191, 51))
        self.commandRun.setObjectName("commandRun")
        self.RunAll = QtWidgets.QPushButton(self.centralwidget)
        self.RunAll.setGeometry(QtCore.QRect(530, 930, 81, 23))
        self.RunAll.setObjectName("RunAll")
        self.DownloadTable = QtWidgets.QPushButton(self.centralwidget)
        self.DownloadTable.setGeometry(QtCore.QRect(1090, 930, 111, 23))
        self.DownloadTable.setObjectName("DownloadTable")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1130, 20, 91, 81))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/newPrefix/GSAW_icon_small.png"))
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_105.setText(_translate("MainWindow", "Pre-Process"))
        self.checkConversion.setText(_translate("MainWindow", "Conversion of file formats:"))
        self.checkWeight.setText(_translate("MainWindow", "Calculating weights for positions"))
        self.radioMerge.setText(_translate("MainWindow", "Merge tFastas of different\n"
"samples (same regions)"))
        self.radioConcat.setText(_translate("MainWindow", "Concatenate tFastas of the same\n"
"samples (different regions)"))
        self.checkJoin.setText(_translate("MainWindow", "Joining tFasta files:"))
        self.checkIndex.setText(_translate("MainWindow", "Indexing tFasta file"))
        self.radioFa2tFa.setText(_translate("MainWindow", "Fasta -> tFasta"))
        self.radioFa2ms.setText(_translate("MainWindow", "Fasta -> ms"))
        self.radioFa2Fa.setText(_translate("MainWindow", "Fasta -> Fasta"))
        self.radiotFa2Fa.setText(_translate("MainWindow", "tFasta -> Fasta"))
        self.radiotFa2ms.setText(_translate("MainWindow", "tFasta -> ms"))
        self.radioVCF2tFa.setText(_translate("MainWindow", "gVCF -> tFasta"))
        self.labelOutputConv.setText(_translate("MainWindow", "Output file"))
        self.label_107.setText(_translate("MainWindow", "File with the name(s) of\n"
"scaffold(s) and their length"))
        self.openScaffoldConv.setText(_translate("MainWindow", "Browse"))
        self.label_108.setText(_translate("MainWindow", "Input file"))
        self.openInputConv.setText(_translate("MainWindow", "Browse"))
        self.label_110.setText(_translate("MainWindow", "File format conversion (ms/Fasta/tFasta)"))
        self.checkMaskConv.setText(_translate("MainWindow", "Include mask"))
        self.openMaskConv.setText(_translate("MainWindow", "Browse"))
        self.label_42.setText(_translate("MainWindow", "Windows length defined with:"))
        self.radioWindowLengthConv1.setText(_translate("MainWindow", "Physical positions"))
        self.radioWindowLengthConv2.setText(_translate("MainWindow", "Effective positions"))
        self.label_43.setText(_translate("MainWindow", "Number of samples per population"))
        self.checkOrderSamplesConv.setText(_translate("MainWindow", "Specific order of samples:"))
        self.labelOrderSamplesConv.setText(_translate("MainWindow", "Total number of samples"))
        self.label_44.setText(_translate("MainWindow", "Total number of populations"))
        self.labelOrderSamplesConv2.setText(_translate("MainWindow", "Number order of samples"))
        self.checkOutgroupConv.setText(_translate("MainWindow", "Include outgroup"))
        self.checkUnknownPosConv.setText(_translate("MainWindow", "Include unknown positions"))
        self.checkCoordConv.setText(_translate("MainWindow", "File with coordinates\n"
"of each windows"))
        self.openCoordConv.setText(_translate("MainWindow", "Browse"))
        self.checkSlideConv.setText(_translate("MainWindow", "Slide size"))
        self.checkWindowSizeConv.setText(_translate("MainWindow", "Windows size"))
        self.checkIUPACConv.setText(_translate("MainWindow", "Use of IUPAC nomenclature code (only for 2 lineages per sequence)"))
        self.updateConv.setText(_translate("MainWindow", "Update parameters"))
        self.checkWeightConv.setText(_translate("MainWindow", "Include external file with\n"
"weights for positions"))
        self.openWeightConv.setText(_translate("MainWindow", "Browse"))
        self.labelCodeWeight.setText(_translate("MainWindow", "Genetic code (Mandatory for synonymous, nonsynonymous or silent positions):"))
        self.checkGFFWeight.setText(_translate("MainWindow", "GFF file"))
        self.openGFFWeight.setText(_translate("MainWindow", "Browse"))
        self.labelCriteriaWeight.setText(_translate("MainWindow", "Criteria to consider transcripts (coding regions):"))
        self.labelTypeWeight.setText(_translate("MainWindow", "Type of annotated position:"))
        self.label_109.setText(_translate("MainWindow", "Annotation and weight options"))
        self.labelInputWeight.setText(_translate("MainWindow", "Input file"))
        self.openInputWeight.setText(_translate("MainWindow", "Browse"))
        self.labelOutputWeight.setText(_translate("MainWindow", "Output weights file "))
        self.checkMaskWeight.setText(_translate("MainWindow", "Include mask"))
        self.openMaskWeight.setText(_translate("MainWindow", "Browse"))
        self.checkRegionsWeight.setText(_translate("MainWindow", "Specify regions to be weighted"))
        self.openRegionsWeight.setText(_translate("MainWindow", "Browse"))
        self.updateWeight.setText(_translate("MainWindow", "Update parameters"))
        self.labelScaffoldWeight.setText(_translate("MainWindow", "File with the name(s) of\n"
"scaffold(s) and their length"))
        self.openScaffoldWeight.setText(_translate("MainWindow", "Browse"))
        self.radioCode1Weight.setText(_translate("MainWindow", "Nuclear Universal"))
        self.radioCode3Weight.setText(_translate("MainWindow", "mtDNA Mammals"))
        self.radioCode2Weight.setText(_translate("MainWindow", "mtDNA Drosophila"))
        self.radioCode4Weight.setText(_translate("MainWindow", "Other"))
        self.radioMaxWeight.setText(_translate("MainWindow", "Maximum combined\n"
"transcribed region"))
        self.radioFirstWeight.setText(_translate("MainWindow", "First transcript"))
        self.radioLongWeight.setText(_translate("MainWindow", "The longest transcript"))
        self.radioMinWeight.setText(_translate("MainWindow", "Minimum shared\n"
"transcribed region"))
        self.checkOutgroupWeight.setText(_translate("MainWindow", "Include outgroup"))
        self.labelOutgroupWeight.setText(_translate("MainWindow", "Number of samples in the outgroup"))
        self.label_114.setText(_translate("MainWindow", "Joining tFasta files"))
        self.labelInputJoin.setText(_translate("MainWindow", "Input list of files"))
        self.openInputJoin.setText(_translate("MainWindow", "Browse"))
        self.label_117.setText(_translate("MainWindow", "Output name"))
        self.updateJoin.setText(_translate("MainWindow", "Update parameters"))
        self.label_118.setText(_translate("MainWindow", "Indexing tFasta file"))
        self.labelInputIndex.setText(_translate("MainWindow", "Input file"))
        self.openInputIndex.setText(_translate("MainWindow", "Browse"))
        self.updateIndex.setText(_translate("MainWindow", "Update parameters"))
        self.label_120.setText(_translate("MainWindow", "Conversion from gVCF to tFasta"))
        self.label_121.setText(_translate("MainWindow", "gVCF file"))
        self.openInputVCF.setText(_translate("MainWindow", "Browse"))
        self.labelOutputVCF.setText(_translate("MainWindow", "Output name"))
        self.label_123.setText(_translate("MainWindow", "Reference Fasta"))
        self.openInputRefFasta.setText(_translate("MainWindow", "Browse"))
        self.label_124.setText(_translate("MainWindow", "File with the name(s) of\n"
"scaffold(s) and their length"))
        self.openScaffoldVCF.setText(_translate("MainWindow", "Browse"))
        self.updateVCF.setText(_translate("MainWindow", "Update parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.preprocess), _translate("MainWindow", "Pre-Process"))
        self.label_7.setText(_translate("MainWindow", "Format file:"))
        self.label_6.setText(_translate("MainWindow", "Output"))
        self.labelOutput.setText(_translate("MainWindow", "Output name"))
        self.updateOutput.setText(_translate("MainWindow", "Update"))
        self.radioFormat0.setText(_translate("MainWindow", "Extended"))
        self.radioFormat1.setText(_translate("MainWindow", "Single line/window"))
        self.radioFormat2.setText(_translate("MainWindow", "Single line SFS/window"))
        self.radioFormat3.setText(_translate("MainWindow", "dadi-like format"))
        self.radioFormat4.setText(_translate("MainWindow", "Single line pairwise distribution"))
        self.radioFormat5.setText(_translate("MainWindow", "Single line freq. variant per line/window"))
        self.radioFormat6.setText(_translate("MainWindow", "SNP genotype matrix"))
        self.radioFormat7.setText(_translate("MainWindow", "SweepFiinder format"))
        self.radioFormat10.setText(_translate("MainWindow", "Full extended"))
        self.label_12.setText(_translate("MainWindow", "Parameters for MS"))
        self.label_13.setText(_translate("MainWindow", "Length"))
        self.checkMSiter.setText(_translate("MainWindow", "ms iterations"))
        self.checkMSratio.setText(_translate("MainWindow", "Ratio transitions/transversions"))
        self.checkMSoutgroup.setText(_translate("MainWindow", "Force analysis to include outgroup"))
        self.checkMSRev.setText(_translate("MainWindow", "Frequency of reverted mutations"))
        self.updateMS.setText(_translate("MainWindow", "Update parameters"))
        self.checkMaskMS.setText(_translate("MainWindow", "Include mask"))
        self.openMaskMS.setText(_translate("MainWindow", "Browse"))
        self.label_17.setText(_translate("MainWindow", "Parameters for Fasta"))
        self.checkGFF.setText(_translate("MainWindow", "GFF file"))
        self.openGFF.setText(_translate("MainWindow", "Browse"))
        self.labelCode.setText(_translate("MainWindow", "Genetic code (synonymous, nonsynonymous or silent positions):"))
        self.labelCriteria.setText(_translate("MainWindow", "Criteria to consider transcripts (coding regions):"))
        self.checkMaskFasta.setText(_translate("MainWindow", "Make a MASK file with the valid positions"))
        self.updateFasta.setText(_translate("MainWindow", "Update parameters"))
        self.checkIUPACFasta.setText(_translate("MainWindow", "Use of IUPAC nomenclature code (only for 2 lineages per sequence)"))
        self.labelType.setText(_translate("MainWindow", "Type of annotated position:"))
        self.radioCode1.setText(_translate("MainWindow", "Nuclear Universal"))
        self.radioCode3.setText(_translate("MainWindow", "mtDNA Mammals"))
        self.radioCode2.setText(_translate("MainWindow", "mtDNA Drosophila"))
        self.radioCode4.setText(_translate("MainWindow", "Other"))
        self.radioMax.setText(_translate("MainWindow", "Maximum combined\n"
"transcribed region"))
        self.radioFirst.setText(_translate("MainWindow", "First transcript"))
        self.radioMin.setText(_translate("MainWindow", "Minimum shared\n"
"transcribed region"))
        self.radioLong.setText(_translate("MainWindow", "The longest transcript"))
        self.label_23.setText(_translate("MainWindow", "Parameters for tFasta"))
        self.checkSlide.setText(_translate("MainWindow", "Slide size"))
        self.label_24.setText(_translate("MainWindow", "Window lengths defined with:"))
        self.label_26.setText(_translate("MainWindow", "File with weights\n"
"for positions"))
        self.openWeights.setText(_translate("MainWindow", "Browse"))
        self.updateTFasta.setText(_translate("MainWindow", "Update parameters"))
        self.radioWindowLengthTF1.setText(_translate("MainWindow", "Physical positions"))
        self.radioWindowLengthTF2.setText(_translate("MainWindow", "Effective positions"))
        self.radioWindowSize.setText(_translate("MainWindow", "Window size"))
        self.radioCoordTF.setText(_translate("MainWindow", "File with coordinates\n"
"of each windows"))
        self.openCoordTF.setText(_translate("MainWindow", "Browse"))
        self.checkFirstWindowTF.setText(_translate("MainWindow", "First window size displacement"))
        self.label_4.setText(_translate("MainWindow", "Format file:"))
        self.label_3.setText(_translate("MainWindow", "Input"))
        self.radioMS.setText(_translate("MainWindow", "MS (simulation analysis)"))
        self.radioFasta.setText(_translate("MainWindow", "Fasta (single-locus analysis)"))
        self.radioTFasta.setText(_translate("MainWindow", "tFasta (genomic analysis using sliding windows)"))
        self.label.setText(_translate("MainWindow", "Input file"))
        self.openInput.setText(_translate("MainWindow", "Browse"))
        self.checkOutgroup.setText(_translate("MainWindow", "Include outgroup"))
        self.checkUnknownPos.setText(_translate("MainWindow", "Include unknown positions"))
        self.label_10.setText(_translate("MainWindow", "Optimal Test:"))
        self.label_8.setText(_translate("MainWindow", "General Parameters"))
        self.label_27.setText(_translate("MainWindow", "Total number of populations"))
        self.label_28.setText(_translate("MainWindow", "Number of samples per population"))
        self.labelOrderSamples1.setText(_translate("MainWindow", "Total number of samples"))
        self.labelOrderSamples2.setText(_translate("MainWindow", "Number order of samples"))
        self.checkOrderSamples.setText(_translate("MainWindow", "Specific order of samples:"))
        self.checkSeed.setText(_translate("MainWindow", "Seed"))
        self.checkPermWindows.setText(_translate("MainWindow", "Permutations per window"))
        self.updateGeneralParam.setText(_translate("MainWindow", "Update Parameters"))
        self.checkAltSpect.setText(_translate("MainWindow", "Alternative Spectrum file"))
        self.openAltSpect.setText(_translate("MainWindow", "Browse"))
        self.checkNullSpect.setText(_translate("MainWindow", "Null Spectrum file"))
        self.openNullSpect.setText(_translate("MainWindow", "Browse"))
        self.label_25.setText(_translate("MainWindow", "File with the name(s) of scaffold(s) and their length"))
        self.openScaffold.setText(_translate("MainWindow", "Browse"))
        self.label_2.setText(_translate("MainWindow", "mstatspop Parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mstatspop), _translate("MainWindow", "mstatspop Parameters"))
        self.label_111.setText(_translate("MainWindow", "Post-Process"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.postprocess), _translate("MainWindow", "Post-Process"))
        self.RunAll.setText(_translate("MainWindow", "Run"))
        self.DownloadTable.setText(_translate("MainWindow", "Download Table"))
import icon_rc
